### ISSUE TITLE
White background with two 4240x7122 jpg images

### ISSUE THREAD

**Issue by harryhow** [timknapen/ofxGiantImage#2]
Hi @timknapen 

I have two large jpg images (4240x7122 @ 4.9MB for each), I only see the white images after applying ofxGiantImage adddon. I guess the tricky part is I'm displaying these images into one large w:2304 x h:8192 screen. (This is the value of from ofGetWidth and ofGetHeight) 
(The target hardware is Mac Mini 2.6GH i5, 8G ram, Intel Iris 1536MB) 

I've also tried to change tileSize to 512/2 or 512x2, it's still not working. I also debug with drawBounds() but I couldn't see any grids on the screen. 
(BTW, the image is displayed ok under 27inch (2560x1440) MBP 2.8 i7, 8G ram, Intel Iris 1536MB. Mac OS 10.10, oF 0.8.4)

Any hints to solve this problem?

Thanks!!

**Comment by timknapen** [comment]
I don't understand the problem. What do you mean with "I see white images with applying the ofxgiantimage addon"? Could you show some code or show a screenshot?

**Comment by harryhow** [comment]
Thanks @timknapen . It's because of my bad for draw image coordination. Not because of large image render. Thanks for your reply. I've successfully loaded two large images by using you addon. :100: :+1:

**Comment by timknapen** [comment]
Great! Good luck!
